version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: mais_subscription_app
        volumes:
            - /home/static_files:/var/www/static_files
            - build-assets:/var/www/html/public/subscription/build 
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
        networks:
            - app-network


    webserver:
        image: nginx:alpine
        container_name: mais_subscription_server
        volumes:
            - ./public/subscription/assets:/var/www/html/public/subscription/assets
            - /home/static_files:/var/www/static_files 
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - build-assets:/var/www/html/public/subscription/build  # Add this line
        ports:
            - "7090:80"
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    build-assets:  
